export const START_IMAGE_FETCHING = "START_IMAGE_FETCHING";
export const SUCCESS_IMAGE_FETCHING = "SUCCESS_IMAGE_FETCHING";
export const FAILED_IMAGE_FETCHING = "FAILED_IMAGE_FETCHING";

export const TOGGLE_IMAGE_SELECT = "TOGGLE_IMAGE_SELECT";
export const TOGGLE_IMAGE_GRID = "TOGGLE_IMAGE_GRID";
